from typing import Optional


class Language:
    def __init__(self, code, name):
        self.code = code
        self.name = name


class Languages:
    EN = Language('en', 'English')
    RU = Language('ru', 'Russian')
    ES = Language('es', 'Spanish')
    DE = Language('de', 'German')
    FR = Language('fr', 'French')
    IT = Language('it', 'Italian')
    JA = Language('ja', 'Japanese')
    KO = Language('ko', 'Korean')
    ZH = Language('zh', 'Chinese')
    AR = Language('ar', 'Arabic')
    TR = Language('tr', 'Turkish')
    PT_BR = Language('pt-br', 'Brazilian Portuguese')
    AF = Language('af', 'Afrikaans')
    SQ = Language('sq', 'Albanian')
    AM = Language('am', 'Amharic')
    HY = Language('hy', 'Armenian')
    AZ = Language('az', 'Azerbaijani')
    EU = Language('eu', 'Basque')
    BE = Language('be', 'Belarusian')
    BN = Language('bn', 'Bengali')
    BS = Language('bs', 'Bosnian')
    BG = Language('bg', 'Bulgarian')
    CA = Language('ca', 'Catalan')
    CEB = Language('ceb', 'Cebuano')
    NY = Language('ny', 'Chichewa')
    ZH_CN = Language('zh-cn', 'Chinese (Simplified)')
    ZH_TW = Language('zh-tw', 'Chinese (Traditional)')
    CO = Language('co', 'Corsican')
    HR = Language('hr', 'Croatian')
    CS = Language('cs', 'Czech')
    DA = Language('da', 'Danish')
    NL = Language('nl', 'Dutch')
    EO = Language('eo', 'Esperanto')
    ET = Language('et', 'Estonian')
    TL = Language('tl', 'Filipino')
    FI = Language('fi', 'Finnish')
    FY = Language('fy', 'Frisian')
    GL = Language('gl', 'Galician')
    KA = Language('ka', 'Georgian')
    EL = Language('el', 'Greek')
    GU = Language('gu', 'Gujarati')
    HT = Language('ht', 'Haitian Creole')
    HA = Language('ha', 'Hausa')
    HAW = Language('haw', 'Hawaiian')
    HE = Language('he', 'Hebrew')
    HI = Language('hi', 'Hindi')
    HMN = Language('hmn', 'Hmong')
    HU = Language('hu', 'Hungarian')
    IS = Language('is', 'Icelandic')
    IG = Language('ig', 'Igbo')
    ID = Language('id', 'Indonesian')
    GA = Language('ga', 'Irish')
    JW = Language('jw', 'Javanese')
    KN = Language('kn', 'Kannada')
    KK = Language('kk', 'Kazakh')
    KM = Language('km', 'Khmer')
    RW = Language('rw', 'Kinyarwanda')
    KY = Language('ky', 'Kyrgyz')
    LO = Language('lo', 'Lao')
    LA = Language('la', 'Latin')
    LV = Language('lv', 'Latvian')
    LT = Language('lt', 'Lithuanian')
    LB = Language('lb', 'Luxembourgish')
    MK = Language('mk', 'Macedonian')
    MG = Language('mg', 'Malagasy')
    MS = Language('ms', 'Malay')
    ML = Language('ml', 'Malayalam')
    MT = Language('mt', 'Maltese')
    MI = Language('mi', 'Maori')
    MR = Language('mr', 'Marathi')
    MN = Language('mn', 'Mongolian')
    MY = Language('my', 'Myanmar (Burmese)')
    NE = Language('ne', 'Nepali')
    NO = Language('no', 'Norwegian')
    OR = Language('or', 'Odia (Oriya)')
    PS = Language('ps', 'Pashto')
    FA = Language('fa', 'Persian')
    PL = Language('pl', 'Polish')
    PT = Language('pt', 'Portuguese')
    PA = Language('pa', 'Punjabi')
    RO = Language('ro', 'Romanian')
    SM = Language('sm', 'Samoan')
    GD = Language('gd', 'Scots Gaelic')
    SR = Language('sr', 'Serbian')
    ST = Language('st', 'Sesotho')
    SN = Language('sn', 'Shona')
    SD = Language('sd', 'Sindhi')
    SI = Language('si', 'Sinhala')
    SK = Language('sk', 'Slovak')
    SL = Language('sl', 'Slovenian')
    SO = Language('so', 'Somali')
    SU = Language('su', 'Sundanese')
    SW = Language('sw', 'Swahili')
    SV = Language('sv', 'Swedish')
    TG = Language('tg', 'Tajik')
    TA = Language('ta', 'Tamil')
    TT = Language('tt', 'Tatar')
    TE = Language('te', 'Telugu')
    TH = Language('th', 'Thai')
    UK = Language('uk', 'Ukrainian')
    UR = Language('ur', 'Urdu')
    UZ = Language('uz', 'Uzbek')
    VI = Language('vi', 'Vietnamese')
    CY = Language('cy', 'Welsh')
    XH = Language('xh', 'Xhosa')
    YI = Language('yi', 'Yiddish')
    YO = Language('yo', 'Yoruba')
    ZU = Language('zu', 'Zulu')

    @classmethod
    def get(cls, code: str) -> Optional[Language]:
        return cls.__getattribute__(cls, code.upper())
        #return next((lang for lang in cls.__dict__ if isinstance(lang, Language) and lang.code == code), None)